### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by amongusenjoyer69** [Spaceman-1001/TitanPublicRelease#1]
auxol sent cp?!?! LOL HES 12

**Comment by Spaceman-1001** [comment]
IKR

**Comment by Auxol** [comment]
proof?

**Comment by Auxol** [comment]
these kids spreading rumours that i sent cp cause i said i wont work on his client with him anymore xD

**Comment by Spaceman-1001** [comment]
Me and beddupe both saw it and we were questioning why someone is so sore in the head to send child porn burn in hell you peophile your disgusting

**Comment by Spaceman-1001** [comment]
If you never sent it why did you leave every server you were in when we brought it up in kinda sus

**Comment by amongusenjoyer69** [comment]
> these kids spreading rumours that i sent cp cause i said i wont work on his client with him anymore xD

how do you expect us to believe you when you lie about being 13????
