### ISSUE TITLE
Cope Harder

### ISSUE THREAD

**Issue by Auxol** [Spaceman-1001/TitanPublicRelease#2]
Cope Harder by spreading more fake news without proof then blocking me when i ask for proof.

keep coping kid

**Comment by Spaceman-1001** [comment]
Why are you deflecting

Me and beddupe both saw what you sent and its disgusting

**Comment by Auxol** [comment]
proof? and would u please not block me this time when i ask for it? otherwise keep coping for clout and the fact that you begged me to continue titan with you in dms, ur "revenge" isnt working kid

**Comment by amongusenjoyer69** [comment]
LOL going into the 7th grade????

**Comment by Auxol** [comment]
no going into high school, also who tf r u and get a brain, they have already been exposed lmao
